#!/bin/bash

# Add this line to .zshrc file to import aliases: source $HOME/.aliases

alias bashconfig="vim ~/.dotfiles/.bashrc"

alias ls="ls --color=always"
alias ll="ls -lhaGtr --color=always"
alias bat="batcat"

alias k="kubectl"
alias kg="kubectl get"
alias kc="kubectl config"
alias dc="docker compose"
# alias ipython="$HOME/$SCRIPTS_DIR/start_ipython.sh"
alias dps="docker container ls -a"

# Go
alias gore="~/go/bin/gore"

# Git
alias gco="git checkout "
alias gb="git branch "
alias gl="git log"
alias gs="git status"
alias gc="git commit -m "

# Aliases for common dirs
alias home="cd ~"

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
